[server]

# The port where the server will listen for browser connections.
port = 8504

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# pastas as quais não devem serem monitoradas para se reexecutar a aplicação em caso de mudanças
folderWatchBlacklist = []

# The base path for the URL where Streamlit should be served from.
# Default: ""
baseUrlPath = ""

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 200